---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/10 0010 14:10
---

GameObject = UnityEngine.GameObject
Transform = UnityEngine.Transform
ParticleSystem = UnityEngine.ParticleSystem
Color = UnityEngine.Color
SceneManagement = UnityEngine.SceneManagement
Input = UnityEngine.Input
KeyCode = UnityEngine.KeyCode
Time = UnityEngine.Time
Camera = UnityEngine.Camera
AudioSource = UnityEngine.AudioSource
Resources = UnityEngine.Resources
www = UnityEngine.WWW
Canvas = UnityEngine.Canvas
GraphicRaycaster = UnityEngine.UI.GraphicRaycaster
Util = Utils
Log = Log
---@type ResManager
ResMgr = ResManager