//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_GradientWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Gradient), typeof(System.Object));
		L.RegFunction("Evaluate", Evaluate);
		L.RegFunction("SetKeys", SetKeys);
		L.RegFunction("New", _CreateUnityEngine_Gradient);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("colorKeys", get_colorKeys, set_colorKeys);
		L.RegVar("alphaKeys", get_alphaKeys, set_alphaKeys);
		L.RegVar("mode", get_mode, set_mode);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_Gradient(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.Gradient obj = new UnityEngine.Gradient();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.Gradient.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Evaluate(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)ToLua.CheckObject(L, 1, typeof(UnityEngine.Gradient));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Color o = obj.Evaluate(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetKeys(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)ToLua.CheckObject(L, 1, typeof(UnityEngine.Gradient));
			UnityEngine.GradientColorKey[] arg0 = ToLua.CheckStructArray<UnityEngine.GradientColorKey>(L, 2);
			UnityEngine.GradientAlphaKey[] arg1 = ToLua.CheckStructArray<UnityEngine.GradientAlphaKey>(L, 3);
			obj.SetKeys(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_colorKeys(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)o;
			UnityEngine.GradientColorKey[] ret = obj.colorKeys;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index colorKeys on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_alphaKeys(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)o;
			UnityEngine.GradientAlphaKey[] ret = obj.alphaKeys;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index alphaKeys on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)o;
			UnityEngine.GradientMode ret = obj.mode;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_colorKeys(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)o;
			UnityEngine.GradientColorKey[] arg0 = ToLua.CheckStructArray<UnityEngine.GradientColorKey>(L, 2);
			obj.colorKeys = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index colorKeys on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_alphaKeys(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)o;
			UnityEngine.GradientAlphaKey[] arg0 = ToLua.CheckStructArray<UnityEngine.GradientAlphaKey>(L, 2);
			obj.alphaKeys = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index alphaKeys on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Gradient obj = (UnityEngine.Gradient)o;
			UnityEngine.GradientMode arg0 = (UnityEngine.GradientMode)ToLua.CheckObject(L, 2, typeof(UnityEngine.GradientMode));
			obj.mode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mode on a nil value");
		}
	}
}

